-- Create table for Dynamic Sake Types (Master Data)
create table if not exists sake_types (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table sake_types enable row level security;

-- Policy: Everyone can read
create policy "Allow public read access"
    on sake_types for select
    using (true);

-- Policy: Authenticated users can insert (implicitly via server actions, but good to have)
-- Actually, we might restrict this to service role if we handle it strictly in actions, 
-- but since we want users to "add" types, we might allow it or handle it purely server-side.
-- For now, let's allow authenticated insert to be flexible, though actions will likely bypass RLS using service role or standard client.
create policy "Allow authenticated insert"
    on sake_types for insert
    with check (auth.role() = 'authenticated');
